version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:10
commands:
  install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm test
  build:
    steps:
      - checkout
      - run:
          name: Build
          command: npm build
workflows:
  version: 2
  build-deploy:
    jobs:
      - test-only:
          filters:
            branches:
              ignore:
                - master
      - release:
          filters:
            branches:
              only:
                - master
jobs:
  test-only:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - install
      - test
  release:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - install
      - test
      - build
      - run:
          name: Netlify Deploy
          command: npm run deploy
