version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:10
workflows:
  version: 2
  build-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
jobs:
  install:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm test
  deploy:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build
          command: npm build
      - run:
          name: Deploy
          command: npm run deploy
